using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SharpIpp.Generators;

[Generator]
public class ValidationSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static s => s != null)
            .Select(static (s, _) => s!);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            Execute(source.Left, source.Right, spc);
        });
    }

    internal static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> classes, SourceProductionContext context)
    {
        var ippValidationAttrSymbol = compilation.GetTypeByMetadataName("SharpIpp.Validation.IppValidationAttribute");
        if (ippValidationAttrSymbol == null)
            return;

        var targetTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var typeSymbol in classes)
        {
            if (typeSymbol.IsAbstract || typeSymbol.IsStatic || typeSymbol.TypeKind != TypeKind.Class || typeSymbol.IsGenericType)
                continue;

            var ns = (typeSymbol.ContainingNamespace == null || typeSymbol.ContainingNamespace.IsGlobalNamespace) ? "" : typeSymbol.ContainingNamespace.ToDisplayString();
            if (ns.StartsWith("SharpIpp.Exceptions") || ns.StartsWith("SharpIpp.Generators") || ns.StartsWith("SharpIpp.Validation"))
                continue;

            if (ns.StartsWith("SharpIpp.Models") || ns.StartsWith("SharpIpp.Protocol.Models") || HasValidationAttributes(typeSymbol, ippValidationAttrSymbol))
            {
                targetTypes.Add(typeSymbol);
            }
        }

        if (targetTypes.Count == 0)
            return;

        // Order descending by inheritance depth so most-derived types come first in switch (obj)
        var sortedTypes = targetTypes
            .OrderByDescending(GetInheritanceDepth)
            .ThenBy(t => t.ToDisplayString())
            .ToList();

        var methodNames = new Dictionary<INamedTypeSymbol, string>(SymbolEqualityComparer.Default);
        foreach (var type in sortedTypes)
        {
            var safeMethodName = "Validate_" + type.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_");
            methodNames[type] = safeMethodName;
        }

        var attrExpressions = new Dictionary<string, (string TypeName, string FieldName)>();
        var attrCounter = 0;

        // Group types by containing namespace to emit separate partial class files
        var typesByNamespace = sortedTypes
            .GroupBy(t => (t.ContainingNamespace == null || t.ContainingNamespace.IsGlobalNamespace) ? "" : t.ContainingNamespace.ToDisplayString())
            .OrderBy(g => g.Key)
            .ToList();

        foreach (var group in typesByNamespace)
        {
            var ns = group.Key;
            var nsSb = new StringBuilder();
            nsSb.AppendLine("// <auto-generated/>");
            nsSb.AppendLine("#nullable enable");
            nsSb.AppendLine();
            nsSb.AppendLine("using System;");
            nsSb.AppendLine("using System.Collections;");
            nsSb.AppendLine("using System.Collections.Generic;");
            nsSb.AppendLine("using System.Text;");
            nsSb.AppendLine();
            nsSb.AppendLine("namespace SharpIpp.Validation");
            nsSb.AppendLine("{");
            nsSb.AppendLine("    internal static partial class GeneratedModelValidator");
            nsSb.AppendLine("    {");

            foreach (var type in group)
            {
                var typeFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var safeMethodName = methodNames[type];

                nsSb.AppendLine($"        private static void {safeMethodName}(");
                nsSb.AppendLine($"            {typeFqn} obj,");
                nsSb.AppendLine("            Encoding encoding,");
                nsSb.AppendLine("            List<string> results,");
                nsSb.AppendLine("            HashSet<object> visited)");
                nsSb.AppendLine("        {");

                var properties = GetAllPublicProperties(type);
                foreach (var prop in properties)
                {
                    var valAttrs = GetValidationAttributes(prop, ippValidationAttrSymbol);
                    if (valAttrs.Count > 0)
                    {
                        nsSb.AppendLine($"            // Validate property: {prop.Name}");
                        nsSb.AppendLine($"            var val_{prop.Name} = obj.{prop.Name};");
                        nsSb.AppendLine($"            var ctx_{prop.Name} = new global::SharpIpp.Validation.ValidationContext(encoding, \"{prop.Name}\");");

                        foreach (var attr in valAttrs)
                        {
                            var expr = FormatAttributeCreation(attr);
                            if (!attrExpressions.TryGetValue(expr, out var attrField))
                            {
                                var fieldName = $"__attr_{attrCounter++}";
                                var attrTypeName = attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                attrField = (attrTypeName, fieldName);
                                attrExpressions[expr] = attrField;
                            }

                            nsSb.AppendLine($"            var res_{prop.Name}_{attrField.FieldName} = {attrField.FieldName}.IsValid(val_{prop.Name}, ctx_{prop.Name});");
                            nsSb.AppendLine($"            if (res_{prop.Name}_{attrField.FieldName} != null && !res_{prop.Name}_{attrField.FieldName}.IsSuccess && res_{prop.Name}_{attrField.FieldName}.ErrorMessage != null)");
                            nsSb.AppendLine($"                results.Add(res_{prop.Name}_{attrField.FieldName}.ErrorMessage);");
                        }
                    }

                    // Child object or collection recursion
                    var unwrappedType = UnwrapNullableAndIppValue(prop.Type, out bool isIppValue);
                    if (isIppValue)
                    {
                        if (IsSharpIppModelType(unwrappedType, compilation.Assembly))
                        {
                            nsSb.AppendLine($"            if (obj.{prop.Name} != null && obj.{prop.Name}.Value.IsValue && obj.{prop.Name}.Value.Value != null)");
                            nsSb.AppendLine($"                TryValidate(obj.{prop.Name}.Value.Value, encoding, results, visited);");
                        }
                        else if (unwrappedType is IArrayTypeSymbol arrType && arrType.ElementType.TypeKind == TypeKind.Class && arrType.ElementType.SpecialType != SpecialType.System_String)
                        {
                            nsSb.AppendLine($"            if (obj.{prop.Name} != null && obj.{prop.Name}.Value.IsValue && obj.{prop.Name}.Value.Value != null)");
                            nsSb.AppendLine("            {");
                            nsSb.AppendLine($"                foreach (var item in obj.{prop.Name}.Value.Value)");
                            nsSb.AppendLine("                {");
                            nsSb.AppendLine("                    if (item != null)");
                            nsSb.AppendLine("                        TryValidate(item, encoding, results, visited);");
                            nsSb.AppendLine("                }");
                            nsSb.AppendLine("            }");
                        }
                        else if (IsGenericEnumerableOfClass(unwrappedType))
                        {
                            nsSb.AppendLine($"            if (obj.{prop.Name} != null && obj.{prop.Name}.Value.IsValue && obj.{prop.Name}.Value.Value != null)");
                            nsSb.AppendLine("            {");
                            nsSb.AppendLine($"                foreach (var item in obj.{prop.Name}.Value.Value)");
                            nsSb.AppendLine("                {");
                            nsSb.AppendLine("                    if (item != null)");
                            nsSb.AppendLine("                        TryValidate(item, encoding, results, visited);");
                            nsSb.AppendLine("                }");
                            nsSb.AppendLine("            }");
                        }
                    }
                    else if (IsSharpIppModelType(prop.Type, compilation.Assembly))
                    {
                        nsSb.AppendLine($"            if (obj.{prop.Name} != null)");
                        nsSb.AppendLine($"                TryValidate(obj.{prop.Name}, encoding, results, visited);");
                    }
                    else if (prop.Type is IArrayTypeSymbol arrayType)
                    {
                        if (arrayType.ElementType.TypeKind == TypeKind.Class && arrayType.ElementType.SpecialType != SpecialType.System_String)
                        {
                            nsSb.AppendLine($"            if (obj.{prop.Name} != null)");
                            nsSb.AppendLine("            {");
                            nsSb.AppendLine($"                foreach (var item in obj.{prop.Name})");
                            nsSb.AppendLine("                {");
                            nsSb.AppendLine("                    if (item != null)");
                            nsSb.AppendLine("                        TryValidate(item, encoding, results, visited);");
                            nsSb.AppendLine("                }");
                            nsSb.AppendLine("            }");
                        }
                    }
                    else if (IsGenericEnumerableOfClass(prop.Type))
                    {
                        nsSb.AppendLine($"            if (obj.{prop.Name} != null)");
                        nsSb.AppendLine("            {");
                        nsSb.AppendLine($"                foreach (var item in obj.{prop.Name})");
                        nsSb.AppendLine("                {");
                        nsSb.AppendLine("                    if (item != null)");
                        nsSb.AppendLine("                        TryValidate(item, encoding, results, visited);");
                        nsSb.AppendLine("                }");
                        nsSb.AppendLine("            }");
                    }
                }

                nsSb.AppendLine("        }");
                nsSb.AppendLine();
            }

            nsSb.AppendLine("    }");
            nsSb.AppendLine("}");

            var hintName = string.IsNullOrEmpty(ns)
                ? "GeneratedModelValidator.Global.g.cs"
                : $"GeneratedModelValidator.{ns}.g.cs";
            context.AddSource(hintName, SourceText.From(nsSb.ToString(), Encoding.UTF8));
        }

        // Generate core partial class file with cached attributes and dispatch switch
        var mainSb = new StringBuilder();
        mainSb.AppendLine("// <auto-generated/>");
        mainSb.AppendLine("#nullable enable");
        mainSb.AppendLine();
        mainSb.AppendLine("using System;");
        mainSb.AppendLine("using System.Collections.Generic;");
        mainSb.AppendLine("using System.Text;");
        mainSb.AppendLine();
        mainSb.AppendLine("namespace SharpIpp.Validation");
        mainSb.AppendLine("{");
        mainSb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        mainSb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"SharpIpp.Generators\", \"1.0.0.0\")]");
        mainSb.AppendLine("    internal static partial class GeneratedModelValidator");
        mainSb.AppendLine("    {");

        // Generate static attribute instances
        mainSb.AppendLine("        #region Cached Validation Attributes");
        foreach (var kvp in attrExpressions)
        {
            var expr = kvp.Key;
            var (typeName, fieldName) = kvp.Value;
            mainSb.AppendLine($"        private static readonly {typeName} {fieldName} = {expr};");
        }
        mainSb.AppendLine("        #endregion");
        mainSb.AppendLine();

        // Generate TryValidate dispatch method
        mainSb.AppendLine("        public static bool TryValidate(");
        mainSb.AppendLine("            object? obj,");
        mainSb.AppendLine("            Encoding encoding,");
        mainSb.AppendLine("            List<string> results,");
        mainSb.AppendLine("            HashSet<object> visited)");
        mainSb.AppendLine("        {");
        mainSb.AppendLine("            if (obj == null)");
        mainSb.AppendLine("                return true;");
        mainSb.AppendLine();
        mainSb.AppendLine("            if (obj is string || obj is ValueType)");
        mainSb.AppendLine("                return true;");
        mainSb.AppendLine();
        mainSb.AppendLine("            if (visited.Contains(obj))");
        mainSb.AppendLine("                return true;");
        mainSb.AppendLine();
        mainSb.AppendLine("            switch (obj)");
        mainSb.AppendLine("            {");

        foreach (var type in sortedTypes)
        {
            var typeFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = methodNames[type];
            mainSb.AppendLine($"                case {typeFqn} target:");
            mainSb.AppendLine("                    visited.Add(obj);");
            mainSb.AppendLine($"                    {methodName}(target, encoding, results, visited);");
            mainSb.AppendLine("                    return true;");
        }

        mainSb.AppendLine("                default:");
        mainSb.AppendLine("                    return false;");
        mainSb.AppendLine("            }");
        mainSb.AppendLine("        }");
        mainSb.AppendLine("    }");
        mainSb.AppendLine("}");

        context.AddSource("GeneratedModelValidator.g.cs", SourceText.From(mainSb.ToString(), Encoding.UTF8));
    }

    internal static IEnumerable<INamedTypeSymbol> GetTypeAndBaseTypes(INamedTypeSymbol? type)
    {
        var curr = type;
        while (curr != null && curr.SpecialType != SpecialType.System_Object)
        {
            yield return curr;
            curr = curr.BaseType;
        }
    }

    internal static int GetInheritanceDepth(INamedTypeSymbol type)
    {
        int depth = 0;
        foreach (var _ in GetTypeAndBaseTypes(type.BaseType))
        {
            depth++;
        }
        return depth;
    }

    private static bool HasValidationAttributes(INamedTypeSymbol typeSymbol, INamedTypeSymbol ippValidationAttrSymbol)
    {
        var properties = GetAllPublicProperties(typeSymbol);
        foreach (var prop in properties)
        {
            if (GetValidationAttributes(prop, ippValidationAttrSymbol).Count > 0)
                return true;
        }
        return false;
    }

    private static List<IPropertySymbol> GetAllPublicProperties(INamedTypeSymbol typeSymbol)
    {
        var properties = new List<IPropertySymbol>();
        var visitedNames = new HashSet<string>();

        foreach (var curr in GetTypeAndBaseTypes(typeSymbol))
        {
            foreach (var member in curr.GetMembers())
            {
                if (member is IPropertySymbol prop &&
                    prop.DeclaredAccessibility == Accessibility.Public &&
                    !prop.IsStatic &&
                    prop.GetMethod != null &&
                    prop.Parameters.Length == 0 &&
                    visitedNames.Add(prop.Name))
                {
                    properties.Add(prop);
                }
            }
        }

        return properties;
    }

    private static List<AttributeData> GetValidationAttributes(IPropertySymbol prop, INamedTypeSymbol ippValidationAttrSymbol)
    {
        var list = new List<AttributeData>();
        foreach (var attr in prop.GetAttributes())
        {
            if (InheritsFrom(attr.AttributeClass, ippValidationAttrSymbol))
            {
                if (IsTautologicalRange(attr, prop.Type))
                    continue;

                list.Add(attr);
            }
        }
        return list;
    }

    internal static bool IsTautologicalRange(AttributeData attr, ITypeSymbol propType)
    {
        if (!IsOrInheritsFrom(attr.AttributeClass, "RangeAttribute"))
            return false;

        if (!IsIntegerTypeOrCollection(propType))
            return false;

        if (attr.ConstructorArguments.Length == 2)
        {
            if (attr.ConstructorArguments[0].Value is int min && min == int.MinValue &&
                attr.ConstructorArguments[1].Value is int max && max == int.MaxValue)
            {
                return true;
            }
        }
        else if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Kind == TypedConstantKind.Array)
        {
            var values = attr.ConstructorArguments[0].Values;
            if (values.Length == 2 &&
                values[0].Value is int min && min == int.MinValue &&
                values[1].Value is int max && max == int.MaxValue)
            {
                return true;
            }
        }

        return false;
    }

    internal static bool IsOrInheritsFrom(ITypeSymbol? symbol, string typeName)
    {
        var curr = symbol;
        while (curr != null)
        {
            if (curr.Name == typeName)
                return true;
            curr = curr.BaseType;
        }
        return false;
    }

    internal static bool IsIntegerTypeOrCollection(ITypeSymbol type)
    {
        if (type == null)
            return false;

        if (IsInt32(type))
            return true;

        if (type is IArrayTypeSymbol arrayType)
            return IsInt32(arrayType.ElementType);

        var ifaces = type.TypeKind == TypeKind.Interface ? type.AllInterfaces.Prepend((INamedTypeSymbol)type) : type.AllInterfaces;
        foreach (var iface in ifaces)
        {
            if (iface.ConstructedFrom.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T &&
                IsInt32(iface.TypeArguments[0]))
            {
                return true;
            }
        }

        return false;
    }

    internal static bool IsInt32(ITypeSymbol type)
    {
        if (type == null)
            return false;

        if (type.SpecialType == SpecialType.System_Int32)
            return true;

        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            return named.TypeArguments[0].SpecialType == SpecialType.System_Int32;

        return false;
    }

    internal static bool InheritsFrom(ITypeSymbol? symbol, ITypeSymbol? baseType)
    {
        if (symbol == null || baseType == null)
            return false;

        var curr = symbol;
        while (curr != null)
        {
            if (SymbolEqualityComparer.Default.Equals(curr, baseType))
                return true;
            curr = curr.BaseType;
        }
        return false;
    }

    internal static bool IsSharpIppModelType(ITypeSymbol type, IAssemblySymbol currentAssembly)
    {
        if (type == null)
            return false;
        if (type.TypeKind != TypeKind.Class)
            return false;
        if (type.SpecialType != SpecialType.None)
            return false;
        if (!SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
            return false;

        var ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        if (ns.StartsWith("SharpIpp.Exceptions") || ns.StartsWith("SharpIpp.Generators") || ns.StartsWith("SharpIpp.Validation"))
            return false;

        return true;
    }

    private static ITypeSymbol UnwrapNullableAndIppValue(ITypeSymbol type, out bool isIppValue)
    {
        isIppValue = false;
        var curr = type;
        if (curr is INamedTypeSymbol n && n.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && n.TypeArguments.Length > 0)
        {
            curr = n.TypeArguments[0];
        }
        if (curr is INamedTypeSymbol named && named.Name == "IppValue" && named.TypeArguments.Length == 1)
        {
            isIppValue = true;
            return named.TypeArguments[0];
        }
        return type;
    }

    private static bool IsGenericEnumerableOfClass(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String)
            return false;

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.IsGenericType && iface.ConstructedFrom.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
            {
                var elemType = iface.TypeArguments[0];
                return elemType.TypeKind == TypeKind.Class && elemType.SpecialType != SpecialType.System_String;
            }
        }

        return false;
    }

    private static string FormatAttributeCreation(AttributeData attr)
    {
        var typeName = attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ctorArgs = string.Join(", ", attr.ConstructorArguments.Select(FormatTypedConstant));

        if (attr.NamedArguments.Length == 0)
        {
            return $"new {typeName}({ctorArgs})";
        }

        var namedArgs = string.Join(", ", attr.NamedArguments.Select(na => $"{na.Key} = {FormatTypedConstant(na.Value)}"));
        return $"new {typeName}({ctorArgs}) {{ {namedArgs} }}";
    }

    internal static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull)
            return "null";

        if (constant.Kind == TypedConstantKind.Array)
        {
            var elemType = ((IArrayTypeSymbol)constant.Type!).ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var items = new string[constant.Values.Length];
            for (var idx = 0; idx < constant.Values.Length; idx++)
            {
                items[idx] = FormatTypedConstant(constant.Values[idx]);
            }
            return $"new {elemType}[] {{ {string.Join(", ", items)} }}";
        }

        if (constant.Kind == TypedConstantKind.Enum)
        {
            return $"({constant.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})({constant.Value})";
        }

        if (constant.Kind == TypedConstantKind.Type)
        {
            return $"typeof({((ITypeSymbol)constant.Value!).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})";
        }

        if (constant.Value is string str)
        {
            return SymbolDisplay.FormatLiteral(str, true);
        }

        if (constant.Value is bool b)
        {
            return b ? "true" : "false";
        }

        if (constant.Value is char c)
        {
            return SymbolDisplay.FormatLiteral(c, true);
        }

        if (constant.Value is int i)
        {
            if (i == int.MaxValue) return "int.MaxValue";
            if (i == int.MinValue) return "int.MinValue";
            return i.ToString();
        }

        if (constant.Value is long l)
        {
            if (l == long.MaxValue) return "long.MaxValue";
            if (l == long.MinValue) return "long.MinValue";
            return $"{l}L";
        }

        return constant.Value!.ToString();
    }
}
