using System.Collections.Generic;

namespace SharpIpp.Protocol.Models
{
    public static class PrinterAttribute
    {
        public const string CharsetSupported = "charset-supported";
        public const string PrinterUriSupported = "printer-uri-supported";
        public const string UriSecuritySupported = "uri-security-supported";
        public const string UriAuthenticationSupported = "uri-authentication-supported";
        public const string PrinterName = "printer-name";
        public const string PrinterLocation = "printer-location";
        public const string PrinterInfo = "printer-info";
        public const string PrinterMoreInfo = "printer-more-info";
        public const string PrinterDriverInstaller = "printer-driver-installer";
        public const string PrinterMakeAndModel = "printer-make-and-model";
        public const string PrinterMoreInfoManufacturer = "printer-more-info-manufacturer";
        public const string PrinterState = "printer-state";
        public const string PrinterStateReasons = "printer-state-reasons";
        public const string PrinterStateMessage = "printer-state-message";
        public const string PrinterDetailedStatusMessages = "printer-detailed-status-messages";
        public const string PrinterStateChangeTime = "printer-state-change-time";
        public const string PrinterStateChangeDateTime = "printer-state-change-date-time";
        public const string PrinterConfigChangeTime = "printer-config-change-time";
        public const string PrinterConfigChangeDateTime = "printer-config-change-date-time";
        public const string PrinterConfigChanges = "printer-config-changes";
        public const string PrinterContactCol = "printer-contact-col";
        public const string PrinterGeoLocation = "printer-geo-location";
        public const string PrinterIds = "printer-ids";
        public const string PrinterImpressionsCompleted = "printer-impressions-completed";
        public const string PrinterImpressionsCompletedCol = "printer-impressions-completed-col";
        public const string PrinterMediaSheetsCompleted = "printer-media-sheets-completed";
        public const string PrinterMediaSheetsCompletedCol = "printer-media-sheets-completed-col";
        public const string PrinterPagesCompleted = "printer-pages-completed";
        public const string PrinterPagesCompletedCol = "printer-pages-completed-col";
        public const string IppVersionsSupported = "ipp-versions-supported";
        public const string OperationsSupported = "operations-supported";
        public const string MultipleDocumentJobsSupported = "multiple-document-jobs-supported";
        public const string MultipleDocumentHandlingDefault = "multiple-document-handling-default";
        public const string MultipleDocumentHandlingSupported = "multiple-document-handling-supported";
        public const string CharsetConfigured = "charset-configured";
        public const string NaturalLanguageConfigured = "natural-language-configured";
        public const string GeneratedNaturalLanguageSupported = "generated-natural-language-supported";
        public const string DocumentFormatDefault = "document-format-default";
        public const string DocumentFormatSupported = "document-format-supported";
        public const string PrinterIsAcceptingJobs = "printer-is-accepting-jobs";
        public const string QueuedJobCount = "queued-job-count";
        public const string PrinterMessageFromOperator = "printer-message-from-operator";
        public const string ColorSupported = "color-supported";
        public const string ReferenceUriSchemesSupported = "reference-uri-schemes-supported";
        public const string PdlOverrideSupported = "pdl-override-supported";
        public const string OverridesSupported = "overrides-supported";
        public const string PrinterUpTime = "printer-up-time";
        public const string PrinterCurrentTime = "printer-current-time";
        public const string MultipleOperationTimeOut = "multiple-operation-time-out";
        public const string CompressionDefault = "compression-default";
        public const string CompressionSupported = "compression-supported";
        public const string JobKOctetsSupported = "job-k-octets-supported";
        public const string JpegKOctetsSupported = "jpeg-k-octets-supported";
        public const string PdfKOctetsSupported = "pdf-k-octets-supported";
        public const string JobImpressionsSupported = "job-impressions-supported";
        public const string JobMediaSheetsSupported = "job-media-sheets-supported";
        public const string JobSheetsDefault = "job-sheets-default";
        public const string JobSheetsSupported = "job-sheets-supported";
        public const string NumberUpDefault = "number-up-default";
        public const string NumberUpSupported = "number-up-supported";
        public const string PagesPerMinute = "pages-per-minute";
        public const string PagesPerMinuteColor = "pages-per-minute-color";
        public const string PrintScalingSupported = "print-scaling-supported";
        public const string PrintScalingDefault = "print-scaling-default";
        public const string MediaDefault = "media-default";
        public const string MediaSupported = "media-supported";
        public const string MediaReady = "media-ready";
        public const string SidesDefault = "sides-default";
        public const string SidesSupported = "sides-supported";
        public const string FinishingsDefault = "finishings-default";
        public const string FinishingsSupported = "finishings-supported";
        public const string PrinterResolutionDefault = "printer-resolution-default";
        public const string PrinterResolutionSupported = "printer-resolution-supported";
        public const string PrintQualityDefault = "print-quality-default";
        public const string PrintQualitySupported = "print-quality-supported";
        public const string JobPriorityDefault = "job-priority-default";
        public const string JobPrioritySupported = "job-priority-supported";
        public const string CopiesDefault = "copies-default";
        public const string CopiesSupported = "copies-supported";
        public const string OrientationRequestedDefault = "orientation-requested-default";
        public const string OrientationRequestedSupported = "orientation-requested-supported";
        public const string PageRangesSupported = "page-ranges-supported";
        public const string JobHoldUntilDefault = "job-hold-until-default";
        public const string JobHoldUntilSupported = "job-hold-until-supported";
        public const string OutputBinDefault = "output-bin-default";
        public const string OutputBinSupported = "output-bin-supported";
        public const string MediaColDefault = "media-col-default";
        public const string MediaColSupported = "media-col-supported";
        public const string MediaColReady = "media-col-ready";
        public const string PrintColorModeDefault = "print-color-mode-default";
        public const string PrintColorModeSupported = "print-color-mode-supported";
        public const string WhichJobsSupported = "which-jobs-supported";
        public const string PrinterUUID = "printer-uuid";
        public const string PdfVersionsSupported = "pdf-versions-supported";
        public const string IppFeaturesSupported = "ipp-features-supported";
        public const string MediaTypeSupported = "media-type-supported";
        public const string DocumentCreationAttributesSupported = "document-creation-attributes-supported";
        public const string JobAccountIdDefault = "job-account-id-default";
        public const string JobAccountIdSupported = "job-account-id-supported";
        public const string JobAccountingUserIdDefault = "job-accounting-user-id-default";
        public const string JobAccountingUserIdSupported = "job-accounting-user-id-supported";
        public const string JobAccountTypeDefault = "job-account-type-default";
        public const string JobAccountTypeSupported = "job-account-type-supported";
        public const string JobCancelAfterDefault = "job-cancel-after-default";
        public const string JobCancelAfterSupported = "job-cancel-after-supported";
        public const string JobSpoolingSupported = "job-spooling-supported";
        public const string MaxPageRangesSupported = "max-page-ranges-supported";
        public const string ClientInfoSupported = "client-info-supported";
        public const string MaxClientInfoSupported = "max-client-info-supported";
        public const string DocumentCharsetDefault = "document-charset-default";
        public const string DocumentCharsetSupported = "document-charset-supported";
        public const string DocumentFormatDetailsSupported = "document-format-details-supported";
        public const string DocumentNaturalLanguageDefault = "document-natural-language-default";
        public const string DocumentNaturalLanguageSupported = "document-natural-language-supported";
        public const string JobIdsSupported = "job-ids-supported";
        public const string JobMandatoryAttributesSupported = "job-mandatory-attributes-supported";
        public const string JobSheetsColDefault = "job-sheets-col-default";
        public const string JobSheetsColSupported = "job-sheets-col-supported";
        public const string PrintContentOptimizeDefault = "print-content-optimize-default";
        public const string PrintContentOptimizeSupported = "print-content-optimize-supported";
        public const string OutputDeviceSupported = "output-device-supported";
        public const string JobCreationAttributesSupported = "job-creation-attributes-supported";
        public const string JobAuthorizationUriSupported = "job-authorization-uri-supported";
        public const string JobPasswordEncryptionSupported = "job-password-encryption-supported";
        public const string FinishingTemplateSupported = "finishing-template-supported";
        public const string FinishingsColSupported = "finishings-col-supported";
        public const string JobPagesPerSetSupported = "job-pages-per-set-supported";
        public const string PunchingHoleDiameterConfigured = "punching-hole-diameter-configured";
        public const string JobDelayOutputUntilDefault = "job-delay-output-until-default";
        public const string JobDelayOutputUntilSupported = "job-delay-output-until-supported";
        public const string JobDelayOutputUntilTimeSupported = "job-delay-output-until-time-supported";
        public const string JobHistoryAttributesConfigured = "job-history-attributes-configured";
        public const string JobHistoryAttributesSupported = "job-history-attributes-supported";
        public const string JobHistoryIntervalConfigured = "job-history-interval-configured";
        public const string JobHistoryIntervalSupported = "job-history-interval-supported";
        public const string JobHoldUntilTimeSupported = "job-hold-until-time-supported";
        public const string JobRetainUntilDefault = "job-retain-until-default";
        public const string JobRetainUntilIntervalDefault = "job-retain-until-interval-default";
        public const string JobRetainUntilIntervalSupported = "job-retain-until-interval-supported";
        public const string JobRetainUntilSupported = "job-retain-until-supported";
        public const string JobRetainUntilTimeSupported = "job-retain-until-time-supported";
        public const string MediaBackCoatingSupported = "media-back-coating-supported";
        public const string MediaBottomMarginSupported = "media-bottom-margin-supported";
        public const string MediaColDatabase = "media-col-database";
        public const string MediaColorSupported = "media-color-supported";
        public const string MediaFrontCoatingSupported = "media-front-coating-supported";
        public const string MediaGrainSupported = "media-grain-supported";
        public const string MediaHoleCountSupported = "media-hole-count-supported";
        public const string MediaKeySupported = "media-key-supported";
        public const string MediaLeftMarginSupported = "media-left-margin-supported";
        public const string MediaOrderCountSupported = "media-order-count-supported";
        public const string MediaPrePrintedSupported = "media-pre-printed-supported";
        public const string MediaRecycledSupported = "media-recycled-supported";
        public const string MediaRightMarginSupported = "media-right-margin-supported";
        public const string MediaSizeSupported = "media-size-supported";
        public const string MediaSourceSupported = "media-source-supported";
        public const string MediaThicknessSupported = "media-thickness-supported";
        public const string MediaToothSupported = "media-tooth-supported";
        public const string MediaTopMarginSupported = "media-top-margin-supported";
        public const string MediaWeightMetricSupported = "media-weight-metric-supported";
        public const string PrinterRequestedClientType = "printer-requested-client-type";
        public const string PrinterFinisher = "printer-finisher";
        public const string PrinterFinisherDescription = "printer-finisher-description";
        public const string PrinterFinisherSupplies = "printer-finisher-supplies";
        public const string PrinterFinisherSuppliesDescription = "printer-finisher-supplies-description";
        public const string FinishingsColDefault = "finishings-col-default";
        public const string FinishingsColReady = "finishings-col-ready";
        public const string BalingTypeSupported = "baling-type-supported";
        public const string BalingWhenSupported = "baling-when-supported";
        public const string BindingReferenceEdgeSupported = "binding-reference-edge-supported";
        public const string BindingTypeSupported = "binding-type-supported";
        public const string CoatingSidesSupported = "coating-sides-supported";
        public const string CoatingTypeSupported = "coating-type-supported";
        public const string CoveringNameSupported = "covering-name-supported";
        public const string FinishingsColDatabase = "finishings-col-database";
        public const string FoldingDirectionSupported = "folding-direction-supported";
        public const string FoldingOffsetSupported = "folding-offset-supported";
        public const string FoldingReferenceEdgeSupported = "folding-reference-edge-supported";
        public const string LaminatingSidesSupported = "laminating-sides-supported";
        public const string LaminatingTypeSupported = "laminating-type-supported";
        public const string PunchingLocationsSupported = "punching-locations-supported";
        public const string PunchingOffsetSupported = "punching-offset-supported";
        public const string PunchingReferenceEdgeSupported = "punching-reference-edge-supported";
        public const string StitchingAngleSupported = "stitching-angle-supported";
        public const string StitchingLocationsSupported = "stitching-locations-supported";
        public const string StitchingMethodSupported = "stitching-method-supported";
        public const string StitchingOffsetSupported = "stitching-offset-supported";
        public const string StitchingReferenceEdgeSupported = "stitching-reference-edge-supported";
        public const string TrimmingOffsetSupported = "trimming-offset-supported";
        public const string TrimmingReferenceEdgeSupported = "trimming-reference-edge-supported";
        public const string TrimmingTypeSupported = "trimming-type-supported";
        public const string TrimmingWhenSupported = "trimming-when-supported";
        public const string CoverBackDefault = "cover-back-default";
        public const string CoverBackSupported = "cover-back-supported";
        public const string CoverFrontDefault = "cover-front-default";
        public const string CoverFrontSupported = "cover-front-supported";
        public const string CoverTypeSupported = "cover-type-supported";
        public const string ForceFrontSideSupported = "force-front-side-supported";
        public const string ImageOrientationDefault = "image-orientation-default";
        public const string ImageOrientationSupported = "image-orientation-supported";
        public const string ImpositionTemplateDefault = "imposition-template-default";
        public const string ImpositionTemplateSupported = "imposition-template-supported";
        public const string InsertCountSupported = "insert-count-supported";
        public const string InsertSheetDefault = "insert-sheet-default";
        public const string InsertSheetSupported = "insert-sheet-supported";
        public const string JobAccountingOutputBinSupported = "job-accounting-output-bin-supported";
        public const string JobAccountingSheetsDefault = "job-accounting-sheets-default";
        public const string JobAccountingSheetsSupported = "job-accounting-sheets-supported";
        public const string JobAccountingSheetsTypeSupported = "job-accounting-sheets-type-supported";
        public const string JobCompleteBeforeSupported = "job-complete-before-supported";
        public const string JobCompleteBeforeTimeSupported = "job-complete-before-time-supported";
        public const string JobErrorSheetDefault = "job-error-sheet-default";
        public const string JobErrorSheetSupported = "job-error-sheet-supported";
        public const string JobErrorSheetTypeSupported = "job-error-sheet-type-supported";
        public const string JobErrorSheetWhenSupported = "job-error-sheet-when-supported";
        public const string JobMessageToOperatorSupported = "job-message-to-operator-supported";
        public const string JobPhoneNumberDefault = "job-phone-number-default";
        public const string JobPhoneNumberSchemeSupported = "job-phone-number-scheme-supported";
        public const string JobPhoneNumberSupported = "job-phone-number-supported";
        public const string JobRecipientNameSupported = "job-recipient-name-supported";
        public const string JobSheetMessageSupported = "job-sheet-message-supported";
        public const string PresentationDirectionNumberUpDefault = "presentation-direction-number-up-default";
        public const string PresentationDirectionNumberUpSupported = "presentation-direction-number-up-supported";
        public const string SeparatorSheetsDefault = "separator-sheets-default";
        public const string SeparatorSheetsSupported = "separator-sheets-supported";
        public const string SeparatorSheetsTypeSupported = "separator-sheets-type-supported";
        public const string XImagePositionDefault = "x-image-position-default";
        public const string XImagePositionSupported = "x-image-position-supported";
        public const string XImageShiftDefault = "x-image-shift-default";
        public const string XImageShiftSupported = "x-image-shift-supported";
        public const string XSide1ImageShiftDefault = "x-side1-image-shift-default";
        public const string XSide2ImageShiftDefault = "x-side2-image-shift-default";
        public const string YImagePositionDefault = "y-image-position-default";
        public const string YImagePositionSupported = "y-image-position-supported";
        public const string YImageShiftDefault = "y-image-shift-default";
        public const string YImageShiftSupported = "y-image-shift-supported";
        public const string YSide1ImageShiftDefault = "y-side1-image-shift-default";
        public const string YSide2ImageShiftDefault = "y-side2-image-shift-default";
        public const string PageDeliveryDefault = "page-delivery-default";
        public const string PageDeliverySupported = "page-delivery-supported";
        public const string PrinterAlert = "printer-alert";
        public const string PrinterAlertDescription = "printer-alert-description";
        public const string PrinterSupply = "printer-supply";
        public const string PrinterSupplyDescription = "printer-supply-description";
        public const string PrinterChargeInfo = "printer-charge-info";
        public const string PrinterChargeInfoUri = "printer-charge-info-uri";
        public const string PrinterMandatoryJobAttributes = "printer-mandatory-job-attributes";
        public const string PrinterRequestedJobAttributes = "printer-requested-job-attributes";
        public const string OutputDeviceUuidSupported = "output-device-uuid-supported";
        public const string DocumentAccessSupported = "document-access-supported";
        public const string FetchDocumentAttributesSupported = "fetch-document-attributes-supported";
        public const string PrinterModeConfigured = "printer-mode-configured";
        public const string PrinterModeSupported = "printer-mode-supported";
        public const string PrinterStaticResourceDirectoryUri = "printer-static-resource-directory-uri";
        public const string PrinterStaticResourceKOctetsSupported = "printer-static-resource-k-octets-supported";
        public const string PrinterStaticResourceKOctetsFree = "printer-static-resource-k-octets-free";

        /// <summary>
        /// The XRI(s) of the Printer object, as requested by the client (operation attribute).
        /// See: PWG 5100.22-2025 Section 7.1.10
        /// </summary>
        public const string PrinterXriSupported = "printer-xri-supported";

        /// <summary>
        /// The URI(s) of the Printer object, as requested by the client (operation attribute).
        /// See: PWG 5100.22-2025 Section 7.1.10
        /// </summary>
        public const string PrinterXriRequested = "printer-xri-requested";
        /// <summary>
        /// The list of resource IDs currently allocated to this Printer (Printer Status attribute).
        /// Defined in PWG 5100.22-2025 Sections 6.1.1 and 6.1.2 (response Group 3: Printer Attributes).
        /// </summary>
        public const string PrinterResourceIds = "printer-resource-ids";
        /// <summary>
        /// The type(s) of print service provided by the Printer.
        /// As operation attribute (1setOf keyword): PWG 5100.22-2025 Section 7.1.9.
        /// As Printer Status attribute (keyword): PWG 5100.22-2025 Section 7.7.9.
        /// </summary>
        public const string PrinterServiceType = "printer-service-type";
        /// <summary>
        /// The accuracy units supported by the 3D Printer.
        /// See: PWG 5100.21-2019 Section 8.1
        /// </summary>
        public const string AccuracyUnitsSupported = "accuracy-units-supported";

        public const string ChamberHumidityDefault = "chamber-humidity-default";
        public const string ChamberHumiditySupported = "chamber-humidity-supported";
        public const string ChamberTemperatureDefault = "chamber-temperature-default";
        public const string ChamberTemperatureSupported = "chamber-temperature-supported";
        public const string MaterialAmountUnitsSupported = "material-amount-units-supported";
        public const string MaterialDiameterSupported = "material-diameter-supported";
        public const string MaterialNozzleDiameterSupported = "material-nozzle-diameter-supported";
        public const string MaterialPurposeSupported = "material-purpose-supported";
        public const string MaterialRateSupported = "material-rate-supported";
        public const string MaterialRateUnitsSupported = "material-rate-units-supported";
        public const string MaterialShellThicknessSupported = "material-shell-thickness-supported";
        public const string MaterialTemperatureSupported = "material-temperature-supported";
        public const string MaterialTypeSupported = "material-type-supported";
        public const string MaterialsColDatabase = "materials-col-database";
        public const string MaterialsColDefault = "materials-col-default";
        public const string MaterialsColReady = "materials-col-ready";
        public const string MaterialsColSupported = "materials-col-supported";
        public const string MaxMaterialsColSupported = "max-materials-col-supported";
        public const string MultipleObjectHandlingDefault = "multiple-object-handling-default";
        public const string MultipleObjectHandlingSupported = "multiple-object-handling-supported";
        public const string PdfFeaturesSupported = "pdf-features-supported";
        public const string PlatformShape = "platform-shape";
        public const string PlatformTemperatureDefault = "platform-temperature-default";
        public const string PlatformTemperatureSupported = "platform-temperature-supported";
        public const string PrintAccuracyDefault = "print-accuracy-default";
        public const string PrintAccuracySupported = "print-accuracy-supported";
        public const string PrintBaseDefault = "print-base-default";
        public const string PrintBaseSupported = "print-base-supported";
        public const string PrintObjectsSupported = "print-objects-supported";
        public const string PrintSupportsDefault = "print-supports-default";
        public const string PrintSupportsSupported = "print-supports-supported";
        public const string PrinterVolumeSupported = "printer-volume-supported";
        public const string ChamberHumidityCurrent = "chamber-humidity-current";
        public const string ChamberTemperatureCurrent = "chamber-temperature-current";

        /// <summary>
        /// The URI(s) of camera image(s) for the 3D Printer.
        /// See: PWG 5100.21-2019 Section 8.17
        /// </summary>
        public const string PrinterCameraImageUri = "printer-camera-image-uri";

        public const string ConfirmationSheetPrintDefault = "confirmation-sheet-print-default";
        public const string CoverSheetInfoDefault = "cover-sheet-info-default";
        public const string CoverSheetInfoSupported = "cover-sheet-info-supported";
        public const string DestinationAccessesSupported = "destination-accesses-supported";
        public const string DestinationUriSchemesSupported = "destination-uri-schemes-supported";
        public const string DestinationUriReady = "destination-uri-ready";
        public const string DestinationUrisSupported = "destination-uris-supported";
        public const string FromNameSupported = "from-name-supported";
        public const string InputAttributesDefault = "input-attributes-default";
        public const string InputAttributesSupported = "input-attributes-supported";
        public const string InputColorModeSupported = "input-color-mode-supported";
        public const string InputContentTypeSupported = "input-content-type-supported";
        public const string InputFilmScanModeSupported = "input-film-scan-mode-supported";
        public const string InputMediaSupported = "input-media-supported";
        public const string InputOrientationRequestedSupported = "input-orientation-requested-supported";
        public const string InputQualitySupported = "input-quality-supported";
        public const string InputResolutionSupported = "input-resolution-supported";
        public const string InputSidesSupported = "input-sides-supported";
        public const string InputSourceSupported = "input-source-supported";
        public const string LogoUriFormatsSupported = "logo-uri-formats-supported";
        public const string LogoUriSchemesSupported = "logo-uri-schemes-supported";
        public const string MessageSupported = "message-supported";
        public const string MultipleDestinationUrisSupported = "multiple-destination-uris-supported";
        public const string NumberOfRetriesDefault = "number-of-retries-default";
        public const string NumberOfRetriesSupported = "number-of-retries-supported";
        public const string OrganizationNameSupported = "organization-name-supported";
        public const string JobDestinationSpoolingSupported = "job-destination-spooling-supported";
        public const string OutputAttributesDefault = "output-attributes-default";
        public const string OutputAttributesSupported = "output-attributes-supported";
        public const string PrinterFaxLogUri = "printer-fax-log-uri";
        public const string PrinterFaxModemInfo = "printer-fax-modem-info";
        public const string PrinterFaxModemName = "printer-fax-modem-name";
        public const string PrinterFaxModemNumber = "printer-fax-modem-number";
        public const string RetryIntervalDefault = "retry-interval-default";
        public const string RetryIntervalSupported = "retry-interval-supported";
        public const string RetryTimeOutDefault = "retry-time-out-default";
        public const string RetryTimeOutSupported = "retry-time-out-supported";
        public const string SubjectSupported = "subject-supported";
        public const string ToNameSupported = "to-name-supported";
    }
}
