name: Test push

on:
  push:
    branches:
      - "master"
      - "v[0-9]*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutput=${{ github.workspace }}/CoverageResults/coverage /p:MergeWith=${{ github.workspace }}/CoverageResults/coverage.json /p:CoverletOutputFormat=\"json,lcov\"
    - name: Publish Native AOT Client Sample
      run: dotnet publish SharpIpp.Samples.Client.NativeAot/SharpIpp.Samples.Client.NativeAot.csproj -c Release -r linux-x64 --self-contained
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@v2
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        file: CoverageResults/coverage.info 

